import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
// import "./book.css";
import "./index.css";
import "./pageFlip3.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
        <body>
        {children}
        </body>
        </html>

    );
}
